export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  REGION_ADMIN = 'REGION_ADMIN',
  PLANTS = 'PLANTS',
  PLANT_ADMIN = 'PLANT_ADMIN',
  CUSTOMER = 'CUSTOMER',
  EMPLOYEE = 'EMPLOYEE',
  SURVEY_TEAM = 'SURVEY_TEAM',
  INSTALLATION_TEAM = 'INSTALLATION_TEAM',
}
